name: Run Rest Assured Test Cases
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
test:
runs-on: macos-latest

steps:
- uses: actions/checkout@v3
- uses: actions/setup-java@v3

with:
distribution: 'temurin'
java-version: '17'

cache: maven
= run: mvn clean test
